---
 - name: debug playbook
   hosts: all
   file-prompt:
    prompt: please enter your website
    private: False
   tasks:
    - name: print hello world
      debug:
       msg: "please visit {{ url }}"
    - name: print msg
      vars:
       - url: www.gremio.com
      debug:
       msg: "please visit {{ url }}"
...