---
 - name: debug playbook
   hosts: all
   vars: 
    - url: www.cloudblitz.com
   tasks:
    - name: print hello world
      debug:
       msg: "please visit {{ url }}"
    - name: print msg
      debug:
       msg: "please visit {{ url }}"
       vars: 
       url: www. gremio.com
...