---
 - name: debug playbook
   hosts: all
   vars: 
    - url: www.cloudblitz.com
   tasks:
    - name: print hello world
      debug:
       msg: "please visit {{ url }}"
    - name: print msg
      vars:
       - url: www.gremio.com
      debug:
       msg: "please visit {{ url }}"
...